ALTER TABLE ride ADD COLUMN created_at TIMESTAMP;

ALTER TABLE ride ADD COLUMN modified_at TIMESTAMP;

ALTER TABLE ride ADD COLUMN created_by VARCHAR(32);

ALTER TABLE ride ADD COLUMN modified_by VARCHAR(32);