spring:
  mvc:
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  liquibase:
    default-schema: taxi_schema


  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: false

  logging:
    level:
      root: INFO
      org.springframework.jdbc.core: TRACE
    file:
      name: taxi.log
      path: /