spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: taxi_schema


  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

  logging:
    level:
      root: DEBUG
    file:
      name: taxi.log
      path: /