spring:
  mvc:
    format:
      date: iso
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
